import { useState } from 'react';
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { Input } from "~/components/Input";
import { api } from "~/utils/api";

export default function Home() {


  const  user  = useUser()
  const {data} = api.moves.getAll.useQuery()
  console.log(user.user?.firstName)

  const [addedPlayer, setAddedPlayer] = useState('');
  const [droppedPlayer, setDroppedPlayer] = useState('');

  const handlePlayerAdd = (player: string) => {
      setAddedPlayer(player)
  };

  const handlePlayerDrop= (player: string) => {
    setDroppedPlayer(player)
  };

  const handleComparison = () => {
    return true;
  }
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-r from-[#373B44] to-[#4286f4]">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          <Input label='added' onChange={handlePlayerAdd} />
          <Input label='dropped' onChange={handlePlayerDrop} />
          {addedPlayer && <h2 className={`my-4 p-4 bg-white text-slate-900 text-center ${ handleComparison() ? 'neon-green-border' : 'neon-red-border'}`}>Added Player: {addedPlayer}</h2>}
          {droppedPlayer && <h2 className={`my-4 p-4 bg-white text-slate-900 text-center ${ handleComparison() ? 'neon-red-border' : 'neon-green-border'}`}>Dropped Player: {droppedPlayer}</h2>}
          {/* {data?.map((move) => (<div key={move.id}>{move.addedPlayer}{move.droppedPlayer}</div>))} */}
        </div>
      </main>
    </>
  );
}
